import type { MediaId } from './media'

/**
 * GENERATED by the media build. Every gallery lists the client's photographs
 * from the matching Downloads folder, in the folder's own order, minus the
 * few files that cannot ship (phone screenshots, third-party watermarks, a
 * stationery flat lay with private contact details, and two unusable
 * behind-the-scenes snapshots).
 */

export const weddingsGallery: readonly MediaId[] = [
  'wed-001', 'wed-002', 'wed-003', 'wed-004', 'wed-005', 'wed-006',
  'wed-007', 'wed-008', 'wed-009', 'wed-010', 'wed-011', 'wed-012',
  'wed-013', 'wed-014', 'wed-015', 'wed-016', 'wed-017', 'wed-018',
  'wed-019', 'wed-020', 'wed-021', 'wed-022', 'wed-023', 'wed-024',
  'wed-025', 'wed-026', 'wed-027', 'wed-028', 'wed-029', 'wed-030',
  'wed-031', 'wed-032', 'wed-033', 'wed-034', 'wed-035', 'wed-036',
  'wed-037', 'wed-038', 'wed-040', 'wed-041', 'wed-042', 'wed-043',
  'wed-044', 'wed-045', 'wed-046', 'wed-047', 'wed-048', 'wed-049',
  'wed-050', 'wed-051', 'wed-052', 'wed-053', 'wed-054', 'wed-055',
  'wed-056', 'wed-057', 'wed-058', 'wed-059', 'wed-060', 'wed-061',
  'wed-062', 'wed-063', 'wed-064', 'wed-065', 'wed-066', 'wed-067',
  'wed-068', 'wed-069', 'wed-070', 'wed-071', 'wed-072', 'wed-073',
  'wed-079', 'wed-080', 'wed-081', 'wed-082', 'wed-083', 'wed-084',
  'wed-085', 'wed-086', 'wed-087', 'wed-088', 'wed-089', 'wed-090',
  'wed-091', 'wed-092', 'wed-093', 'wed-094', 'wed-095', 'wed-096',
  'wed-097', 'wed-098', 'wed-099', 'wed-100', 'wed-101', 'wed-102',
  'wed-103', 'wed-104', 'wed-105', 'wed-106', 'wed-107', 'wed-108',
  'wed-109', 'wed-110', 'wed-111', 'wed-112', 'wed-113', 'wed-114',
  'wed-115', 'wed-116', 'wed-117', 'wed-118', 'wed-119', 'wed-120',
  'wed-121', 'wed-122', 'wed-123', 'wed-124', 'wed-125', 'wed-126',
  'wed-127', 'wed-128', 'wed-129', 'wed-130', 'wed-131', 'wed-132',
  'wed-133', 'wed-134', 'wed-135', 'wed-136', 'wed-137', 'wed-138',
  'wed-139', 'wed-140', 'wed-141', 'wed-142', 'wed-143', 'wed-144',
  'wed-145', 'wed-146', 'wed-147', 'wed-148',
]

export const signatureMomentsGallery: readonly MediaId[] = [
  'sig-001', 'sig-002', 'sig-003', 'sig-004', 'sig-005', 'sig-006',
  'sig-007', 'sig-008', 'sig-009', 'sig-010', 'sig-011', 'sig-012',
  'sig-013', 'sig-014', 'sig-015', 'sig-016', 'sig-017', 'sig-018',
  'sig-019', 'sig-020', 'sig-021', 'sig-022',
]

export const designStylizationGallery: readonly MediaId[] = [
  'design-001', 'design-002', 'design-003', 'design-004', 'design-005', 'design-006',
  'design-007', 'design-008', 'design-009', 'design-010', 'design-011', 'design-012',
  'design-013', 'design-014', 'design-015', 'design-017', 'design-019', 'design-020',
  'design-021', 'design-022', 'design-023', 'design-024', 'design-025', 'design-026',
  'design-027', 'design-028', 'design-029', 'design-030', 'design-031', 'design-032',
  'design-033', 'design-034', 'design-035', 'design-036', 'design-037', 'design-038',
  'design-039', 'design-040', 'design-041', 'design-042', 'design-043', 'design-044',
  'design-045', 'design-046', 'design-047', 'design-048', 'design-049', 'design-050',
  'design-051', 'design-052', 'design-053', 'design-054', 'design-055', 'design-056',
  'design-057', 'design-058', 'design-059', 'design-060', 'design-061', 'design-062',
  'design-063', 'design-064', 'design-065', 'design-066', 'design-067', 'design-068',
  'design-069', 'design-070', 'design-071', 'design-072', 'design-073', 'design-074',
  'design-075', 'design-076', 'design-077', 'design-078', 'design-079', 'design-080',
  'design-081', 'design-082', 'design-083', 'design-084', 'design-085', 'design-086',
  'design-087', 'design-088', 'design-089', 'design-090', 'design-091', 'design-092',
  'design-093', 'design-094', 'design-095', 'design-096', 'design-097', 'design-098',
  'design-099', 'design-100', 'design-101', 'design-102', 'design-103', 'design-104',
  'design-105', 'design-106', 'design-107', 'design-108', 'design-109', 'design-110',
  'design-111', 'design-112', 'design-113', 'design-114', 'design-115', 'design-116',
  'design-118', 'design-119', 'design-125', 'design-126', 'design-127', 'design-128',
  'design-129', 'design-130', 'design-131', 'design-132', 'design-133', 'design-134',
  'design-135', 'design-136', 'design-137', 'design-138', 'design-139', 'design-140',
  'design-141', 'design-142', 'design-143', 'design-144', 'design-145', 'design-146',
  'design-147', 'design-148', 'design-149', 'design-150', 'design-151', 'design-152',
  'design-153', 'design-154', 'design-155', 'design-156', 'design-157', 'design-158',
  'design-159', 'design-160', 'design-161', 'design-162', 'design-163', 'design-164',
  'design-165', 'design-166', 'design-167', 'design-168', 'design-169', 'design-170',
  'design-171', 'design-172', 'design-173', 'design-174', 'design-175', 'design-176',
  'design-177', 'design-178', 'design-179', 'design-180', 'design-181', 'design-182',
  'design-183', 'design-184', 'design-185', 'design-186', 'design-187', 'design-188',
  'design-189', 'design-195', 'design-196', 'design-197',
]

export const workshopsGallery: readonly MediaId[] = [
  'work-001', 'work-002', 'work-003', 'work-004', 'work-005', 'work-006',
  'work-007', 'work-008', 'work-009', 'work-010', 'work-011',
]

export const conferencesGallery: readonly MediaId[] = [
  'conf-001', 'conf-002', 'conf-003', 'conf-004', 'conf-005', 'conf-006',
  'conf-007', 'conf-008', 'conf-009', 'intl-001', 'intl-002', 'intl-003',
  'intl-004', 'intl-005', 'intl-006', 'intl-007', 'intl-008', 'intl-009',
  'intl-010', 'intl-011', 'intl-012', 'intl-013', 'intl-014', 'intl-015',
  'intl-016', 'intl-017', 'intl-018', 'intl-019', 'intl-020', 'intl-021',
  'intl-022', 'intl-023', 'intl-024', 'intl-025', 'intl-026', 'intl-027',
]

export const fundraisingGallery: readonly MediaId[] = [
  'fund-001', 'fund-002', 'fund-003', 'fund-004', 'fund-005', 'fund-006',
  'fund-007', 'fund-008', 'fund-009', 'fund-010', 'fund-011', 'fund-012',
  'fund-013', 'fund-014', 'fund-015', 'fund-016', 'fund-017', 'fund-018',
  'fund-019', 'fund-020', 'fund-021', 'fund-022', 'fund-023', 'fund-024',
  'fund-025', 'fund-026', 'fund-027', 'fund-028', 'fund-029', 'fund-030',
  'fund-031', 'fund-032', 'fund-033', 'fund-034', 'fund-035', 'fund-036',
  'fund-037', 'fund-039', 'fund-040', 'fund-041', 'fund-042', 'fund-043',
  'fund-044', 'fund-045', 'fund-046', 'fund-047', 'fund-048', 'fund-049',
  'fund-050', 'fund-051', 'fund-052', 'fund-053', 'fund-054', 'fund-055',
  'fund-056', 'fund-057', 'fund-058', 'fund-059', 'fund-060', 'fund-061',
  'fund-062', 'fund-063', 'fund-064', 'fund-065', 'fund-066',
]

export const capConsultationGallery: readonly MediaId[] = [
  'consult-001', 'consult-002', 'consult-003',
]

export const capPlanningGallery: readonly MediaId[] = [
  'plan-001', 'plan-002', 'plan-003', 'plan-004', 'plan-005', 'plan-006',
  'plan-007', 'plan-008', 'plan-009', 'plan-010', 'plan-011', 'plan-012',
  'plan-015',
]

export const capDesignProductionGallery: readonly MediaId[] = [
  'design-002', 'design-003', 'design-004', 'design-007', 'design-008', 'design-010',
  'design-013', 'design-015', 'design-020', 'design-021', 'design-054', 'design-070',
  'design-072', 'design-078', 'design-079', 'design-085', 'design-089', 'design-090',
  'design-094', 'design-099', 'design-100', 'design-104', 'design-128', 'design-138',
]

export const capFullExperienceGallery: readonly MediaId[] = [
  'fem-001', 'fem-002', 'fem-003', 'fem-004', 'fem-005', 'fem-006',
  'fem-007', 'fem-008', 'fem-009', 'fem-010', 'fem-011', 'fem-012',
  'fem-013', 'fem-014', 'fem-015', 'fem-018', 'fem-019', 'fem-020',
  'fem-021', 'fem-022', 'fem-023', 'fem-024', 'fem-025', 'fem-026',
  'fem-027',
]

export const featureBridalFantasyGallery: readonly MediaId[] = [
  'feature-bridal-fantasy-1', 'feature-bridal-fantasy-2', 'feat-001', 'feat-002', 'feat-003', 'feat-004',
]

export const featureDancingWithHerGallery: readonly MediaId[] = [
  'dwh-001', 'dwh-002', 'dwh-003', 'dwh-004', 'dwh-005', 'dwh-006',
  'dwh-007', 'dwh-008', 'dwh-009',
]

export const featureMensVowGallery: readonly MediaId[] = [
  'mv-001', 'mv-002', 'mv-003', 'mv-004', 'mv-005', 'mv-006',
  'mv-007', 'mv-008', 'mv-009', 'mv-010', 'mv-011', 'mv-012',
]

export const portfolioGallery: readonly MediaId[] = [
  'wed-028', 'wed-049', 'wed-059', 'wed-062', 'wed-036', 'wed-025',
  'sig-006', 'sig-009', 'sig-010', 'sig-013', 'sig-014', 'sig-022',
  'fund-001', 'fund-008', 'fund-016', 'fund-023', 'fund-030', 'fund-033',
  'conf-009', 'conf-002', 'intl-001', 'intl-006', 'intl-021', 'work-005',
  'design-135', 'design-125', 'design-143', 'design-079', 'design-002', 'design-023',
  'work-001', 'work-009', 'work-010', 'work-011', 'work-003', 'work-006',
]

export const homeStrip: readonly MediaId[] = [
  'wed-049', 'sig-010', 'design-135', 'work-009', 'intl-021', 'fem-013',
]

export const homeFrames: readonly MediaId[] = [
  'home-001', 'home-002', 'home-003', 'home-004', 'home-005', 'home-006',
  'home-007', 'home-009', 'home-010',
]
